blog/urls.py
from blog.models import Category
from blog.views import AboutView, BlogPageView, BlogDetailView
from django.urls import path

urlpatterns = [
    path('post/<int:pk>/', BlogDetailView.as_view(), name = 'post'),
    path('about/',AboutView.as_view(template_name="about.html")),
    path('', BlogPageView.as_view(), name = 'index'),
]

karakayablog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('blog.urls')),
    path('', include('blog.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from ckeditor.fields import RichTextField

class Post(models.Model):
    title = models.CharField(max_length=100, default="")
    description = models.CharField(max_length=250, default="")
    content = RichTextField()
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/',null=True)
    keywords = models.TextField()

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.title

class About(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from blog.models import About, Post
from django.core.paginator import Paginator

class BlogPageView(ListView):
    model = Post
    template_name = 'index.html'
    paginate_by = 5

class BlogDetailView(DetailView):
    model = Post
    template_name = 'post.html'

class AboutView(ListView):
    model = About
    template_name = 'about.html'

templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="card mt-5">
            <div class="card-body">
                {% for polo in about_list %}
                <p>{{ polo.text }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% include 'header.html' %}

{% block content %}

{% endblock %}

{% include 'footer.html' %}

templates/footer.html
<footer>
    <!-- Bootstrap JS -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
    crossorigin="anonymous"></script>
</body>

</html>
</footer>

templates/header.html
<!DOCTYPE html>
<html lang="tr">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- Bootstrap Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/custom.css">

    <title>SametKarakaya.Com.TR</title>
</head>

<body class="bg-dark">

    <section id="header" class="generic">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">SametKarakaya.Com.TR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Main Page</a>
                        </li>


                        
                        <li class="nav-item dropdown">
                            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Categories
                            </a>
                            
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                
                                    <li>
                                    
                                
                                        <a class="dropdown-item" href=""><a>
                                

                                    </li>
                               
                               
                            </ul>
                            
                            
                        </li>
                        
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </section>

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


<section id="content" class="generic">
  <div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for post in object_list %}
      <div class="col">
        <div class="card mt-5">
          <img src="{{ post.image.url }}" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.description }}...</p>
            <input type="button" onclick='window.location="{% url 'post' post.pk %}"' class="col-12 btn btn-outline-dark" value="Read More">
          </div>
          <div class="card-footer">
            <small class="text-muted  d-flex justify-content-center">
              <span class="align-middle">
                <i class="bi bi-calendar"></i> {{post.date |date:"F d, Y"}}
                <i class="bi bi-person-circle"></i> {{post.author}}
              </span>
            </small>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
  <div class="col mt-5 mb-5 d-flex justify-content-center">
    {% if is_paginated %}

    {% if page_obj.number == 1 %}
    <a class="btn btn-outline-info float-right" href="?page=2">Older Posts &rarr;</a>
    {% endif %}

    {% if page_obj.has_previous %}
    <a class="btn btn-outline-info" href="/">&laquo;</a>
    <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
    {% endif %}


    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num and page_obj.number != 1 %}
    <a class="btn btn-outline-info" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next and page_obj.number != 1 %}
    <a class="btn btn-outline-info" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
    <a class="btn btn-outline-info" href="?page={{ page_obj.paginator.num.pages }}">&raquo;</a>
    {% endif %}


    {% endif %}
  </div>
</section>

{% endblock %}

templates/post.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="card mt-5 mb-3 p-0">
            <img src="{{ post.image.url }}" class="card-img-top p-0 m-0 rounded-0">
            <div class="card-footer text-center"><small class="text-muted"><span class="align-middle align-center"><i class="bi bi-calendar"></i> {{post.date |date:"F d, Y"}} <i class="bi bi-person-circle"></i> {{post.author}}</span></small></div>
            <div class="card-body">
              <p class="card-title fs-2 text-center text-warning bg-dark">{{post.title}}</p>
              <p class="card-text">{{post.content|safe}}</p>
            </div>
          </div>
    </div>
</div>

{% endblock %}